
export const dataLevels = [



    {
        id:1,
        title: "Beginner lvl Qestion 1",
        question:'Which unit is more powerful?',
        answer: [`Archangel`, `Black Dragon`, `Titan`, `Lazure Dragon`],
        correctAnswer: 3,
        level: 'beginner',

    },

    {
        id:2,
        title: "Qestion 2",
        question: 'How many gold/day gives you  a capitol?',
        answer: [`3000`, `5000`, `4000`, `40000,`],
        correctAnswer: 2,
        level: 'beginner',

    },
    { id:3,
        title: "Qestion 3",
        question: 'Chose the name of heroe, who have default spell - lightning chain?',
        answer: [`Sandro`, `Solmir`, `Xeron`, `Jog,`],
        correctAnswer: 1,
        level: 'beginner',
    },
    {
        id:4,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to have a double-mana?',
        answer: [`Tower`, `Castle`, `Dungen`, `Inferno,`],
        correctAnswer: 2,
        level: 'beginner',
    },
    {
        id:5,
        title: "Qestion 5",
        question: 'How many items you need to combine a Statue of Legion?',
        answer: [`5`, `6`, `7`, `4,`],
        correctAnswer: 0,
        level: 'beginner',
    },
    {
        id:6,
        title: "Qestion 6",
        question: 'Which artifacte gives you "explosion" spell into your spellbock?',
        answer: [`Wizard's Well`, `Crown of Dragontooth`, `Helm of Chaos`, `Spellbinder's Hat`],
        correctAnswer: 3,
        level: 'beginner',
    },


    {
        id:7,
        title: "Middle lvl Qestion 1",
        question: 'Which unit is more powerful?',
        answer: [`Archangel`, `Black Dragon`, `Titan`, `Lazure Dragon`],
        correctAnswer: 3,
        level: 'middle',
    },
    {
        id:8,
        title: "Qestion 2",
        question: 'How many gold/day gives you  a capitol?',
        answer: [`3000`, `5000`, `4000`, `40000,`],
        correctAnswer: 2,
        level: 'middle',

    },
    { id:9,
        title: "Qestion 3",
        question: 'Chose the name of heroe, who have default spell - lightning chain?',
        answer: [`Sandro`, `Solmir`, `Xeron`, `Jog,`],
        correctAnswer: 1,
        level: 'middle',
    },
    {
        id:10,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to have a double-mana?',
        answer: [`Tower`, `Castle`, `Dungen`, `Inferno,`],
        correctAnswer: 2,
        level: 'middle',
    },
    {
        id:11,
        title: "Qestion 5",
        question: 'How many items you need to combine a Statue of Legion?',
        answer: [`5`, `6`, `7`, `4,`],
        correctAnswer: 0,
        level: 'middle',
    },
    {
        id:12,
        title: "Qestion 6",
        question: 'Which artifacte gives you "explosion" spell into your spellbock?',
        answer: [`Wizard's Well`, `Crown of Dragontooth`, `Helm of Chaos`, `Spellbinder's Hat`],
        correctAnswer: 3,
        level: 'middle',
    },

    {
        id:13,
        title: "Master lvl Qestion 1",
        question:'Which unit is more powerful?',
        answer: [`Archangel`, `Black Dragon`, `Titan`, `Lazure Dragon`],
        correctAnswer: 3,
        level: 'master',

    },

    {
        id:14,
        title: "Qestion 2",
        question: 'How many gold/day gives you  a capitol?',
        answer: [`3000`, `5000`, `4000`, `40000,`],
        correctAnswer: 2,
        level: 'master',

    },
    { id:15,
        title: "Qestion 3",
        question: 'Chose the name of heroe, who have default spell - lightning chain?',
        answer: [`Sandro`, `Solmir`, `Xeron`, `Jog,`],
        correctAnswer: 1,
        level: 'master',
    },
    {
        id:16,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to have a double-mana?',
        answer: [`Tower`, `Castle`, `Dungen`, `Inferno,`],
        correctAnswer: 2,
        level: 'master',
    },
    {
        id:17,
        title: "Qestion 5",
        question: 'How many items you need to combine a Statue of Legion?',
        answer: [`5`, `6`, `7`, `4,`],
        correctAnswer: 0,
        level: 'master',
    },
    {
        id:18,
        title: "Qestion 6",
        question: 'Which artifacte gives you "explosion" spell into your spellbock?',
        answer: [`Wizard's Well`, `Crown of Dragontooth`, `Helm of Chaos`, `Spellbinder's Hat`],
        correctAnswer: 3,
        level: 'master',
    },


    {
        id:19,
        title: "Hardcore lvl Qestion 1",
        question: 'Which unit is more powerful?',
        answer: [`Archangel`, `Black Dragon`, `Titan`, `Lazure Dragon`],
        correctAnswer: 3,
        level: 'hardcore',
    },
    {
        id:20,
        title: "Qestion 2",
        question: 'How many gold/day gives you  a capitol?',
        answer: [`3000`, `5000`, `4000`, `40000,`],
        correctAnswer: 2,
        level: 'hardcore',

    },
    { id:21,
        title: "Qestion 3",
        question: 'Chose the name of heroe, who have default spell - lightning chain?',
        answer: [`Sandro`, `Solmir`, `Xeron`, `Jog,`],
        correctAnswer: 1,
        level: 'hardcore',
    },
    {
        id:22,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to have a double-mana?',
        answer: [`Tower`, `Castle`, `Dungen`, `Inferno,`],
        correctAnswer: 2,
        level: 'hardcore',
    },
    {
        id:23,
        title: "Qestion 5",
        question: 'How many items you need to combine a Statue of Legion?',
        answer: [`5`, `6`, `7`, `4,`],
        correctAnswer: 0,
        level: 'hardcore',
    },
    {
        id:24,
        title: "Qestion 6",
        question: 'Which artifacte gives you "explosion" spell into your spellbock?',
        answer: [`Wizard's Well`, `Crown of Dragontooth`, `Helm of Chaos`, `Spellbinder's Hat`],
        correctAnswer: 3,
        level: 'hardcore',
    },

]
