
export const dataLevels = [



    {
        id:1,
        title: "Beginner lvl Qestion 1",
        question:'Which unit is more powerful?',
        answer: [`Archangel`, `Black Dragon`, `Titan`, `Azure Dragon`],
        correctAnswer: `Lazure Dragon`,
        level: 'beginner',

    },

    {
        id:2,
        title: "Qestion 2",
        question: 'How many gold/day gives you  a capitol?',
        answer: [`3000`, `5000`, `4000`, `40000,`],
        correctAnswer: `4000`,
        level: 'beginner',

    },
    { id:3,
        title: "Qestion 3",
        question: 'Chose the name of heroe, who have default spell - lightning chain?',
        answer: [`Sandro`, `Solmir`, `Xeron`, `Jog,`],
        correctAnswer: `Solmir`,
        level: 'beginner',
    },
    {
        id:4,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to have a double-mana?',
        answer: [`Tower`, `Castle`, `Dungen`, `Inferno,`],
        correctAnswer:`Dungen`,
        level: 'beginner',
    },
    {
        id:5,
        title: "Qestion 5",
        question: 'How many items you need to combine a Statue of Legion?',
        answer: [`5`, `6`, `7`, `4,`],
        correctAnswer: `5`,
        level: 'beginner',
    },
    {
        id:6,
        title: "Qestion 6",
        question: 'Which artifacte gives you "explosion" spell into your spellbock?',
        answer: [`Wizard's Well`, `Crown of Dragontooth`, `Helm of Chaos`, `Spellbinder's Hat`],
        correctAnswer: `Spellbinder's Hat`,
        level: 'beginner',
    },


    {
        id:7,
        title: "Middle lvl Qestion 1",
        question: 'Which unit have the best magic-resist?',
        answer: [`gnome`, `unicorn`, `diamond-golem`, `steel-golem`],
        correctAnswer: `diamond-golem`,
        level: 'middle',
    },
    {
        id:8,
        title: "Qestion 2",
        question: 'In which level of Mage Guild you can learn spell "animate of undead"?',
        answer: [`2`, `3`, `4`, `1,`],
        correctAnswer: `3`,
        level: 'middle',

    },
    { id:9,
        title: "Qestion 3",
        question: 'Chose the artifact that gives you ability to defeat any unit using battle magic',
        answer: [` Titan's Cuirass`, `Sphere of Permanence`, `Orb of Inhibition`,`Orb of Vulnerability`],
        correctAnswer: `Orb of Vulnerability`,
        level: 'middle',
    },
    {
        id:10,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to  see all game-map ?',
        answer: [`Tower`, `Castle`, `Conflux`,`Cove`],
        correctAnswer: `Tower`,
        level: 'middle',
    },
    {
        id:11,
        title: "Qestion 5",
        question: 'Which tier-1 unit is the fastest one?',
        answer: [`pixie`, `centaur`, `oceanid`, `hobgoblin,`],
        correctAnswer: `oceanid`,
        level: 'middle',
    },
    {
        id:12,
        title: "Qestion 6",
        question: 'You want to resurect unit,to save him after battle,exept spell, you need for this:',
        answer: [`Orb of Vulnerability`, `Expert earth magic`, `advanced earth magic`, `Tome of Earth`],
        correctAnswer:`advanced earth magic`,
        level: 'middle',
    },

    {
        id:13,
        title: "Master lvl Qestion 1",
        question:'What the min amount of angels you can have in griffons conservatory (100-200)?',
        answer: [`3`, `4`, `2`, `5`],
        correctAnswer: `2`,
        level: 'master',

    },

    {
        id:14,
        title: "Qestion 2",
        question: 'You have a heroe without spellbook, how it`s posible to have it with 0 gold?',
        answer: [`exchange it with other hero`, `combine some artefacts`, `this is imposible`, `exchange it in artifact market`],
        correctAnswer: `combine some artefacts, for example Titans Thunder` ,
        level: 'master',

    },
    { id:15,
        title: "Qestion 3",
        question: 'Chose the name of heroe, who have default spell - lightning chain?',
        answer: [`Sandro`, `Solmir`, `Xeron`, `Jog,`],
        correctAnswer: `Dungen`,
        level: 'master',
    },
    {
        id:16,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to have a double-mana?',
        answer: [`Tower`, `Castle`, `Dungen`, `Inferno,`],
        correctAnswer: `Dungen`,
        level: 'master',
    },
    {
        id:17,
        title: "Qestion 5",
        question: 'How many items you need to combine a Statue of Legion?',
        answer: [`5`, `6`, `7`, `4,`],
        correctAnswer: `Dungen`,
        level: 'master',
    },
    {
        id:18,
        title: "Qestion 6",
        question: 'Which artifacte gives you "explosion" spell into your spellbock?',
        answer: [`Wizard's Well`, `Crown of Dragontooth`, `Helm of Chaos`, `Spellbinder's Hat`],
        correctAnswer: `Dungen`,
        level: 'master',
    },


    {
        id:19,
        title: "Hardcore lvl Qestion 1",
        question: 'Which unit is more powerful?',
        answer: [`Archangel`, `Black Dragon`, `Titan`, `Lazure Dragon`],
        correctAnswer: `Dungen`,
        level: 'hardcore',
    },
    {
        id:20,
        title: "Qestion 2",
        question: 'How many gold/day gives you  a capitol?',
        answer: [`3000`, `5000`, `4000`, `40000,`],
        correctAnswer: `Dungen`,
        level: 'hardcore',

    },
    { id:21,
        title: "Qestion 3",
        question: 'Chose the name of heroe, who have default spell - lightning chain?',
        answer: [`Sandro`, `Solmir`, `Xeron`, `Jog,`],
        correctAnswer: `Dungen`,
        level: 'hardcore',
    },
    {
        id:22,
        title: "Qestion 4",
        question: 'Which "Town" gives you ability to have a double-mana?',
        answer: [`Tower`, `Castle`, `Dungen`, `Inferno,`],
        correctAnswer: `Dungen`,
        level: 'hardcore',
    },
    {
        id:23,
        title: "Qestion 5",
        question: 'How many items you need to combine a Statue of Legion?',
        answer: [`5`, `6`, `7`, `4,`],
        correctAnswer: `Dungen`,
        level: 'hardcore',
    },
    {
        id:24,
        title: "Qestion 6",
        question: 'Which artifacte gives you "explosion" spell into your spellbock?',
        answer: [`Wizard's Well`, `Crown of Dragontooth`, `Helm of Chaos`, `Spellbinder's Hat`],
        correctAnswer: `Dungen`,
        level: 'hardcore',
    },

]
